# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlueskyTerminal < Formula
  desc ""
  homepage "https://github.com/jibraniqbal666/homebrew-bluesky-terminal"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jibraniqbal666/homebrew-bluesky-terminal/releases/download/v0.0.1/bluesky-terminal_Darwin_x86_64.tar.gz"
      sha256 "cdceddeb5ffa139b50efa74aa633277c88f8a3adbe8d70a393187b06f5684317"

      def install
        bin.install "bluesky-terminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jibraniqbal666/homebrew-bluesky-terminal/releases/download/v0.0.1/bluesky-terminal_Darwin_arm64.tar.gz"
      sha256 "6dc2feed30d7510fcf842a0015da460f10ea92d26df540b83c0dbe1f16b934d6"

      def install
        bin.install "bluesky-terminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jibraniqbal666/homebrew-bluesky-terminal/releases/download/v0.0.1/bluesky-terminal_Linux_x86_64.tar.gz"
        sha256 "e1da2e409e99a1c935ee5c72b42a2a574e16ea19c9869b5ab04c46a45d8676a7"

        def install
          bin.install "bluesky-terminal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jibraniqbal666/homebrew-bluesky-terminal/releases/download/v0.0.1/bluesky-terminal_Linux_arm64.tar.gz"
        sha256 "eac078da64933037c236e5c2c224f861dd8097bf701ccd255a25da161828dd40"

        def install
          bin.install "bluesky-terminal"
        end
      end
    end
  end
end
